"""
MIGRATION-META:
  source_path: packages/nodes-base/credentials/Mqtt.credentials.ts
  target_context: n8n
  target_layer: Infrastructure
  responsibility: 位于 packages/nodes-base/credentials 的凭证。导入/依赖:外部:无；内部:n8n-workflow；本地:无。导出:Mqtt。关键函数/方法:无。用于声明 n8n 该模块鉴权字段/校验规则，供节点引用。
  entities: []
  external_dependencies: []
  mapping_confidence: High
  todo_refactor_ddd:
    - Detected ICredentialType adapter
    - Rewrite implementation for Infrastructure layer
  moved_in_batch: 2026-01-18-system-analysis-ddd-mapping
"""
# TODO-REFACTOR-DDD: packages/nodes-base/credentials/Mqtt.credentials.ts -> services/n8n/infrastructure/nodes-base/external_services/adapters/credentials/Mqtt_credentials.py

import type { ICredentialType, IDisplayOptions, INodeProperties } from 'n8n-workflow';

export class Mqtt implements ICredentialType {
	name = 'mqtt';

	displayName = 'MQTT';

	documentationUrl = 'mqtt';

	properties: INodeProperties[] = [
		{
			displayName: 'Protocol',
			name: 'protocol',
			type: 'options',
			options: [
				{
					name: 'Mqtt',
					value: 'mqtt',
				},
				{
					name: 'Mqtts',
					value: 'mqtts',
				},
				{
					name: 'Ws',
					value: 'ws',
				},
			],
			default: 'mqtt',
		},
		{
			displayName: 'Host',
			name: 'host',
			type: 'string',
			default: '',
		},
		{
			displayName: 'Port',
			name: 'port',
			type: 'number',
			default: 1883,
		},
		{
			displayName: 'Username',
			name: 'username',
			type: 'string',
			default: '',
		},
		{
			displayName: 'Password',
			name: 'password',
			type: 'string',
			typeOptions: {
				password: true,
			},
			default: '',
		},
		{
			displayName: 'Clean Session',
			name: 'clean',
			type: 'boolean',
			default: true,
			description:
				'Whether to use clean session - set to false to receive QoS 1 and 2 messages while offline',
		},
		{
			displayName: 'Client ID',
			name: 'clientId',
			type: 'string',
			default: '',
			description: 'Client ID. If left empty, one is autogenerated for you.',
		},
		{
			displayName: 'SSL',
			name: 'ssl',
			type: 'boolean',
			default: false,
		},
		{
			displayName: 'Passwordless',
			name: 'passwordless',
			type: 'boolean',
			displayOptions: {
				show: {
					ssl: [true],
				},
			},
			default: true,
			description:
				'Whether to use passwordless connection with certificates (SASL mechanism EXTERNAL)',
		},
		{
			displayName: 'CA Certificates',
			name: 'ca',
			type: 'string',
			typeOptions: {
				password: true,
			},
			displayOptions: {
				show: {
					ssl: [true],
				},
			},
			default: '',
			description: 'SSL CA Certificates to use',
		},
		{
			displayName: 'Reject Unauthorized Certificate',
			name: 'rejectUnauthorized',
			type: 'boolean',
			displayOptions: {
				show: {
					ssl: [true],
					passwordless: [true],
				},
			} as IDisplayOptions,
			default: false,
			description: 'Whether to validate Certificate',
		},
		{
			displayName: 'Client Certificate',
			name: 'cert',
			type: 'string',
			typeOptions: {
				password: true,
			},
			displayOptions: {
				show: {
					ssl: [true],
					passwordless: [true],
				},
			} as IDisplayOptions,
			default: '',
			description: 'SSL Client Certificate to use',
		},
		{
			displayName: 'Client Key',
			name: 'key',
			type: 'string',
			typeOptions: {
				password: true,
			},
			displayOptions: {
				show: {
					ssl: [true],
					passwordless: [true],
				},
			},
			default: '',
			description: 'SSL Client Key to use',
		},
	];
}
